apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-fail
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  labels:
    name: sync-fail
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Source of the application manifests
  source:
    repoURL: https://github.com/olivergondza/argo-test-projs.git
    targetRevision: HEAD
    path: sync-fail/manifests

    # directory
    directory:
      recurse: true
      # exclude: 'config.yaml'
      include: '*.yaml'

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - SkipDryRunOnMissingResource=true # Allow skip dry run on missing resource
    - CreateNamespace=true

    # The retry feature is available since v1.7
    retry:
      limit: -1
